services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-blogpessoal
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: ["java", "-jar", "/app.jar"]
    networks:
      - blogpessoal-net

networks:
  blogpessoal-net:
    driver: bridge

